version: "3.7"

services:
  api:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  api:
